version: '2'
services:
  my-mongo-data:
    build: ./my-mongo-data
  andrew-app:
    build: ./my-node-app/
    ports:
    - "3000:3000"
    links:
    - andrew-api
    depends_on:
    - andrew-api
    environment:
    - PAPI_URL=$PAPI_URL_AWS
    # - my-nodejs
  andrew-api:
    build: ./my-node-api/
    ports:
    - "3001:3000"
    links:
    - andrew-db
    depends_on:
    - andrew-db
    # - my-nodejs
  andrew-db:
    build: ./my-mongodb
    ports:
    - "27017:27017"
    volumes_from:
    - my-mongo-data
